Repository cmu-db/benchbase, pull requests merged in 2022-03, with the labels that each got.

#99 Native TPC-H Database Generator
  config/cockroachdb/sample_tpch_config.xml
  config/mariadb/sample_tpch_config.xml
  config/mysql/sample_tpch_config.xml
  config/noisepage/sample_tpch_config.xml
  config/postgres/sample_tpch_config.xml
  pom.xml
  src/main/java/com/oltpbenchmark/benchmarks/tpch/TPCHBenchmark.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/TPCHConstants.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/TPCHLoader.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/TPCHUtil.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q11.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q12.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q13.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q16.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q17.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q2.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q20.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q21.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q3.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q5.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q7.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q8.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/procedures/Q9.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/CopyUtil.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/CustomerGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/Distribution.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/DistributionLoader.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/Distributions.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/GenerateUtils.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/LineItemGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/NationGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/OrderGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/PartGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/PartSupplierGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/RegionGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/SupplierGenerator.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHConstants.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHRandomAlphaNumeric.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHRandomPhoneNumber.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHRandomString.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHRandomStringSequence.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TPCHRandomText.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TextPool.java
  src/main/java/com/oltpbenchmark/benchmarks/tpch/util/TextPoolGenerator.java
  src/main/java/com/oltpbenchmark/util/RowRandomBoundedInt.java
  src/main/java/com/oltpbenchmark/util/RowRandomBoundedLong.java
  src/main/java/com/oltpbenchmark/util/RowRandomInt.java
  src/main/java/com/oltpbenchmark/util/RowRandomLong.java
  src/main/java/com/oltpbenchmark/util/StringUtil.java
  src/main/resources/benchmarks/tpch/dists.dss
  src/test/java/com/oltpbenchmark/benchmarks/tpch/TestTPCHBenchmark.java
  src/test/java/com/oltpbenchmark/benchmarks/tpch/TestTPCHLoader.java
Labels: in-progress

#111 Fixed running benchbase.jar from any directory
  src/main/java/com/oltpbenchmark/DBWorkload.java
Labels: enhancement, ready-to-merge

#121 Resolves Issue 97 - classpath conflicts from various driver jars
  .github/workflows/maven.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/assembly/tgz.xml
  src/main/assembly/zip.xml
Labels: ready-to-merge

#126 Switch txns to return instead of unnecessarily aborting in SEATS
  src/main/java/com/oltpbenchmark/DBWorkload.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/SEATSWorker.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/procedures/DeleteReservation.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/procedures/NewReservation.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/procedures/UpdateCustomer.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/procedures/UpdateReservation.java
  src/main/java/com/oltpbenchmark/benchmarks/seats/util/ErrorType.java
Labels: ready-for-review

#127 resolves #98 - invalid postgres-dialect file breaks HYADAPT benchmark
  src/main/resources/benchmarks/hyadapt/dialect-postgres.xml
Labels: ready-for-review

#129 working on issue #128; adding exec plugin and fixing getClass method
  README.md
  pom.xml
  src/main/java/com/oltpbenchmark/util/ClassUtil.java
Labels: ready-for-review

#131 fixes #130 - allows for comma separated host:port combinations in jdbc urls
  src/main/java/com/oltpbenchmark/DBWorkload.java
Labels: ready-for-review

#136 Two small optimizations for SEATS on CockroachDB
  src/main/resources/benchmarks/seats/ddl-cockroachdb.sql
  src/main/resources/benchmarks/seats/dialect-cockroachdb.xml
Labels: ready-for-review
