Repository cmu-db/benchbase, pull requests merged in 2023-06, with the labels that each got.

#327 Add TRANSACTION_NONE support
  src/main/java/com/oltpbenchmark/WorkloadConfiguration.java
Labels: enhancement, ready-to-merge

#321 YCSB: customizable zipfian constant
  config/cockroachdb/sample_ycsb_config.xml
  config/mariadb/sample_ycsb_config.xml
  config/mysql/sample_ycsb_config.xml
  config/noisepage/sample_ycsb_config.xml
  config/postgres/sample_ycsb_config.xml
  config/spanner/sample_ycsb_config.xml
  config/sqlite/sample_ycsb_config.xml
  config/sqlserver/sample_ycsb_config.xml
  src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBBenchmark.java
  src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBWorker.java
Labels: ready-to-merge

#311 Remove redundant TPC-C index on Order.
  src/main/resources/benchmarks/tpcc/ddl-myrocks.sql
  src/main/resources/benchmarks/tpcc/ddl-mysql.sql
  src/main/resources/benchmarks/tpcc/ddl-noisepage.sql
  src/main/resources/benchmarks/tpcc/ddl-postgres.sql
  src/main/resources/benchmarks/tpcc/ddl-singlestore.sql
Labels: bug, ready-to-merge

#310 Enable rate to be < 1.
  src/main/java/com/oltpbenchmark/DBWorkload.java
  src/main/java/com/oltpbenchmark/Phase.java
  src/main/java/com/oltpbenchmark/ThreadBench.java
  src/main/java/com/oltpbenchmark/WorkloadConfiguration.java
Labels: enhancement, ready-to-merge

#306 Convert unit tests into JUnit4 format
  src/test/java/com/oltpbenchmark/api/AbstractTestBenchmarkModule.java
  src/test/java/com/oltpbenchmark/api/AbstractTestCase.java
  src/test/java/com/oltpbenchmark/api/AbstractTestLoader.java
  src/test/java/com/oltpbenchmark/api/AbstractTestWorker.java
  src/test/java/com/oltpbenchmark/api/TestDDLOverride.java
  src/test/java/com/oltpbenchmark/api/TestProcedure.java
  src/test/java/com/oltpbenchmark/api/TestSQLStmt.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/TestAuctionMarkBenchmark.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/TestAuctionMarkLoader.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/TestAuctionMarkWorker.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/util/TestItemId.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/util/TestUserId.java
  src/test/java/com/oltpbenchmark/benchmarks/auctionmark/util/TestUserIdGenerator.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/TestSEATSBenchmark.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/TestSEATSLoader.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/util/TestCustomerId.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/util/TestCustomerIdIterable.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/util/TestDistanceUtil.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/util/TestFlightId.java
  src/test/java/com/oltpbenchmark/benchmarks/seats/util/TestReturnFlight.java
  src/test/java/com/oltpbenchmark/catalog/TestHSQLDBCatalog.java
  src/test/java/com/oltpbenchmark/util/TestClassUtil.java
  src/test/java/com/oltpbenchmark/util/TestCollectionUtil.java
  src/test/java/com/oltpbenchmark/util/TestFileUtil.java
  src/test/java/com/oltpbenchmark/util/TestHistogram.java
  src/test/java/com/oltpbenchmark/util/TestRandomDistribution.java
  src/test/java/com/oltpbenchmark/util/TestTextGenerator.java
Labels: ready-to-merge, testing
